package utils

import "errors"

var (
	ErrUserNotFound        = errors.New("user not found")
	ErrUserAlreadyExists   = errors.New("user already exists")
	ErrDuplicateUser       = errors.New("duplicate user exists with this username")
	ErrCommandNotFound     = errors.New("command not found")
	ErrTooManyArguments    = errors.New("too many arguments")
	ErrUnknownType         = errors.New("unknown type")
	ErrEmptyCommandHistory = errors.New("empty command history")
	ErrInvalidUsername     = errors.New("invalid username")
	ErrInvalidPassword     = errors.New("invalid password")
	ErrInvalidExitCode     = errors.New("invalid exit code")
	ErrAlreadyLoggedOut    = errors.New("already logged out")
	ErrInvalidArguments    = errors.New("invalid arguments")
	ErrReadingPassword     = errors.New("error reading password")
	ErrWhoYouAre           = errors.New("please tell me who you are")
	ErrNoFileProvided      = errors.New("no file provided")
	ErrFileClosing         = errors.New("error during file closing")
	ErrFileNotFound        = errors.New("no such file or directory")
	ErrFileOpening         = errors.New("error during file opening")
	ErrFileReading         = errors.New("error during file reading")
	ErrMissMatchPasswords  = errors.New("password does not match")
	ErrUsernameNotEntered  = errors.New("username not entered")
	ErrDirectoryNotExists  = errors.New("directory not exists")
	ErrPermissionDenied    = errors.New("permission denied")
	ErrChangingDirectory   = errors.New("error changing directory")
	ErrNoPreviousPath      = errors.New("no previous path")
)
